"use client"

import { useEffect, useRef, useState } from "react"

const documentLines = [
  { type: "heading", content: "# Tzylo Documentation" },
  { type: "comment", content: "Auto-generated by Tzylo Synapse" },
  { type: "separator", content: "---" },
  { type: "empty", content: "" },
  { type: "section-title", content: "## [2025-05-08] Fix: Shifted from submissionId to chunkId" },
  { type: "field", content: "**PR:** #42 | **Author:** @kbpramod" },
  { type: "empty", content: "" },
  { type: "field", content: "**Summary:** Renamed identifier across submission pipeline for consistency" },
  { type: "empty", content: "" },
  { type: "tag", content: "### API Changes" },
  { type: "value", content: "- Updated POST /submit endpoint — field renamed from submissionId to chunkId" },
  { type: "value", content: "- Clients must update request payload to use chunkId" },
  { type: "empty", content: "" },
  { type: "tag", content: "### Breaking Changes" },
  { type: "value", content: "- submissionId no longer accepted — breaking change for existing integrations" },
  { type: "value", content: "- Requires migration for downstream consumers" },
  { type: "empty", content: "" },
  { type: "tag", content: "### Architecture" },
  { type: "value", content: "- Identifier now aligns with chunk-based data model across all services" },
  { type: "empty", content: "" },
  { type: "separator", content: "---" },
  { type: "empty", content: "" },
  { type: "section-title", content: "## [2025-05-06] Feature: Add webhook event system" },
  { type: "field", content: "**PR:** #39 | **Author:** @anurag" },
  { type: "empty", content: "" },
  { type: "field", content: "**Summary:** Implemented webhook event dispatching for real-time integrations" },
  { type: "empty", content: "" },
  { type: "tag", content: "### API Changes" },
  { type: "value", content: "- New POST /webhooks/register endpoint" },
  { type: "value", content: "- New GET /webhooks/events endpoint with pagination" },
  { type: "empty", content: "" },
  { type: "tag", content: "### Configuration" },
  { type: "value", content: "- Added WEBHOOK_SECRET environment variable" },
  { type: "value", content: "- New webhook_events table in database" },
]

export function DocumentationPreview() {
  const [visible, setVisible] = useState(false)
  const [visibleLines, setVisibleLines] = useState(0)
  const sectionRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) setVisible(true)
      },
      { threshold: 0.2 }
    )
    if (sectionRef.current) observer.observe(sectionRef.current)
    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    if (!visible) return
    const timer = setInterval(() => {
      setVisibleLines((prev) => {
        if (prev >= documentLines.length) {
          clearInterval(timer)
          return prev
        }
        return prev + 1
      })
    }, 60)
    return () => clearInterval(timer)
  }, [visible])

  const getLineClass = (type: string) => {
    switch (type) {
      case "heading": return "heading"
      case "comment": return "comment"
      case "separator": return "separator"
      case "section-title": return "section-title"
      case "tag": return "tag"
      case "field": return "field"
      case "value": return "value"
      default: return ""
    }
  }

  return (
    <section className="relative py-28" id="documentation" ref={sectionRef}>
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[1px] bg-gradient-to-r from-transparent via-primary/30 to-transparent" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <span className="text-sm font-semibold text-primary uppercase tracking-widest">Live Preview</span>
          <h2 className="text-4xl sm:text-5xl font-bold text-foreground mt-4 mb-6">
            How{" "}
            <code className="text-primary font-mono bg-primary/10 px-3 py-1 rounded-lg">TZYLO.md</code>
            {" "}looks
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            After just a few PRs, your repository has a complete, searchable history of every meaningful change.
          </p>
        </div>

        {/* Code Preview */}
        <div className="max-w-4xl mx-auto">
          <div className="code-block overflow-hidden">
            {/* Window Chrome */}
            <div className="flex items-center gap-3 px-5 py-4 border-b border-border/50">
              <div className="flex gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500/70" />
                <div className="w-3 h-3 rounded-full bg-yellow-500/70" />
                <div className="w-3 h-3 rounded-full bg-green-500/70" />
              </div>
              <div className="flex-1 flex justify-center">
                <div className="flex items-center gap-2 px-4 py-1 rounded-md bg-secondary/30 text-muted-foreground text-xs">
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
                    <path d="M14 2v6h6" />
                  </svg>
                  TZYLO.md
                </div>
              </div>
              <div className="w-16" /> {/* Spacer for symmetry */}
            </div>

            {/* Code Content */}
            <div className="p-5 overflow-x-auto max-h-[500px] overflow-y-auto">
              {documentLines.map((line, index) => (
                <div
                  key={index}
                  className={`flex transition-all duration-300 ${
                    index < visibleLines ? "opacity-100" : "opacity-0"
                  }`}
                  style={{
                    transitionDelay: `${index * 30}ms`,
                    minHeight: line.type === "empty" ? "1.2rem" : undefined,
                  }}
                >
                  <span className="line-number select-none shrink-0">{index + 1}</span>
                  <span className={getLineClass(line.type)}>
                    {line.content}
                  </span>
                </div>
              ))}
              {/* Cursor blink */}
              {visibleLines < documentLines.length && (
                <div className="flex mt-1">
                  <span className="line-number select-none shrink-0">{visibleLines + 1}</span>
                  <span
                    className="w-2 h-5 bg-primary/70 inline-block"
                    style={{ animation: "typewriter-blink 1s infinite" }}
                  />
                </div>
              )}
            </div>
          </div>

          {/* Caption */}
          <p className="text-center text-sm text-muted-foreground mt-6">
            Every PR adds an entry. Your team always knows what changed and why.
          </p>
        </div>
      </div>
    </section>
  )
}
